name: "Post compare link when flake.lock changes"

runs:
  using: composite
  steps:
  - name: Install nix
    uses: cachix/install-nix-action@v30
    with:
      nix_path: nixpkgs=channel:nixpkgs-unstable

  - name: Generate comment from changed flake.lock file
    shell: bash
    run: |
      export PATH="$PATH:$(nix-build --expr 'with import <nixpkgs> { }; buildEnv { name = "PATH"; paths = [python3Packages.jsonpatch]; }')/bin"

      echo "flake.lock compare links:" > comment.md

      before_rev_flake_lock="$(git log HEAD^ -1 --format='%H' -- flake.lock)"
      before_flake_lock="$(mktemp)"
      git show "$before_rev_flake_lock:flake.lock" > "$before_flake_lock"

      # when debugging, remove extra escape before dollars in xargs
      jsondiff "$before_flake_lock" flake.lock | jq -c '.[] | select(.path|endswith("/rev"))' | \
        xargs -d'\n' bash -c 'in="$1"; \
          locked=$(echo "$in" | jq -r .path | sed -e "s|/rev$||g" -e "s|/|.|g"); \
          old_rev="$(jq -r "$locked.rev" '"$before_flake_lock"')"; \
          new_rev="$(echo "$in" | jq -r .value)"; \
          path="$(jq -r "$locked | \"https://\(.host // \"github.com\")/\(.owner)/\(.repo)/compare\"" flake.lock)"; \
          echo "- $path/$old_rev...$new_rev" \
        ' "" >> comment.md

  - name: Find Comment
    uses: peter-evans/find-comment@v3
    id: fc
    with:
      issue-number: ${{ github.event.pull_request.number }}
      comment-author: 'github-actions[bot]'
      body-includes: flake.lock compare links

  - name: Create or update comment
    uses: peter-evans/create-or-update-comment@v4
    with:
      comment-id: ${{ steps.fc.outputs.comment-id }}
      issue-number: ${{ github.event.pull_request.number }}
      body-path: 'comment.md'
      edit-mode: replace
